version: "3"

services:
  docsig:
    image: wtzbzdev/docsig:latest
    container_name: docsig
    network_mode: "bridge"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - acme:/etc/acme
      - contents:/usr/app
      - certlog:/var/log/cert
    restart: "unless-stopped"

volumes:
   acme:
   certlog:
   contents:
